### ISSUE TITLE
Change the unit of Free RAM to GB

### ISSUE THREAD

**Issue by Hellis81** [GamerClassN7/HA_Desktop_Companion#46]
I doubt anyone needs the value in KB. 
If we make it GB with one decimal then we still get `0.5` for example which should be fine as a value I believe.
Or possibly two decimals.

**Comment by GamerClassN7** [comment]
you can add

```yaml
accuracy_decimals: 2
filters:
 - multiply: 0.5
```

![image](https://user-images.githubusercontent.com/22167469/190085574-74fa355b-5e83-4326-b3bd-03193d35c2fa.png)

if you default one correct values i can use them as default one also i would stick to (MB) not GB for those systems like mi intel computer stick. so default value is still usefull

**Comment by Hellis81** [comment]
Huh...

```
  - platform: wmic
    wmic_path: Win32_OperatingSystem
    wmic_selector: FreePhysicalMemory
    wmic_namespace: \\root\CIMV2
    name: Free Ram
    unique_id: free_ram
    unit_of_measurement: "GB"
    icon: "mdi:clock"
    entity_category: "diagnostic"
    accuracy_decimals: 2
    filters:
     - divide: 1000000
```

![image](https://user-images.githubusercontent.com/61010215/190089218-9ef24307-6eb5-42a2-a501-b16588883078.png)
