### ISSUE TITLE
Sendkeys?

### ISSUE THREAD

**Issue by Hellis81** [GamerClassN7/HA_Desktop_Companion#50]
Does this have the possibility to sendkeys?
Imagine locking and unlocking by using sensors on your phone and computer.

**Comment by GamerClassN7** [comment]
Yeah this should be possible with some work

**Comment by GamerClassN7** [comment]
Partially Implemented

**Comment by Hellis81** [comment]
Interesting. 
Which version is it in? And how is it used?

**Comment by GamerClassN7** [comment]
You need to Enable it in your configuration.yaml since it is a weary dangerous think.  but it can send only one key in one notification, it is published in the latest one.

**Comment by GamerClassN7** [comment]
actually just made automation on my home Media PC to pause/play and mute :D actually nice on incoming calls :)
Closing sinc implemented fully

**Comment by Hellis81** [comment]
It seems to work fine, except two issues.
First, is there a way to make it silent. Not really an issue but can be annoying. This is a low priority.
The second issue is capital and non capital letters.
Sending the commands give by default lower case letters, I tried sending caps lock, letter, caps lock:

```
  - service: notify.mobile_app_debug_axlt2801
    data:
      message: ""
      data:
        key: 0x14
  - service: notify.mobile_app_debug_axlt2801
    data:
      message: ""
      data:
        key: 0x53
  - service: notify.mobile_app_debug_axlt2801
    data:
      message: ""
      data:
        key: 0x14
```

but caps lock remains on, only when I physically press the key on the keyboard does it release. 
Same thing if I try to send a shift button press.
Do you know of a fix for this?
