### ISSUE TITLE
Feature Request: Include Wmi Examples for other Sensors 

### ISSUE THREAD

**Issue by ryanr05** [GamerClassN7/HA_Desktop_Companion#68]
Some ones id like (as I'm a noob to WMI)
Fan Speed(s)- For Use on a Desktop Pc Case
Network Bandwidth
Temps (MB & CPU/GPU)
Storage Usage/Free Space

I'm Confident in editing yaml just don't really know what to insert for the above mentioned sensors
if @GamerClassN7 could post those WMI values id appreciate it or include them into the next update and i can remove any sensors from the Yaml that arent needed (I.e Battery & Charging sensors)

**Comment by GamerClassN7** [comment]
Hello there is problem that 
there is no standard for following 2 (ecah manufactorer have difrent addresses)

- Fan Speed(s)- For Use on a Desktop Pc Case
- Temps (MB & CPU/GPU)

I will try to look in to two below :)
- Network Bandwidth
- Storage Usage/Free Space

most of the time i am just fiddling with: https://www.ks-soft.net/hostmon.eng/wmi/index.htm
to find correct class and selector. :)

**Comment by GamerClassN7** [comment]
Note for me Class Win32_LogicalDisk)

**Comment by ryanr05** [comment]
so for MB fan speeds & temps im currently using this [MB:](https://www.gigabyte.com/Motherboard/GA-H81M-H-rev-10#ov\) GA-H81M-H (rev. 1.0

**Comment by ryanr05** [comment]
> Note for me HDD - Class Win32_LogicalDisk NET - Win32_PerfFormattedData_Tcpip_NetworkInterface / BytesTotalPersec

so what would be the full yaml for those sensors

**Comment by GamerClassN7** [comment]
I need time to test it :) I will try to do it this week I really need to make sure that everything is reliable

**Comment by GamerClassN7** [comment]
![image](https://github.com/GamerClassN7/HA_Desktop_Companion/assets/22167469/532ad3c8-6533-4554-a5ae-2d769985763b)

```yaml
 - platform: wmic
   wmic_class: Win32_LogicalDisk
   wmic_selector: FreeSpace
   wmic_namespace: root\CIMV2
   name: "C Free Disk space"
   unique_id: disk_0_space
   icon: "mdi:tape-drive"
   unit_of_measurement: "GB"
   entity_category: "diagnostic"
   update_interval: 10
   filters:
     - divide: 1073741824
   accuracy_decimals: 1
```

I will need to put out new version in order to support iterrable values - multiple drives and multiple network cards
but it is dooable :) 

On other site i dont have any GB motherboard and i was not able to found information's on the internet, so until someone sends me correct WMI query i am unable to provide template for  Temperatures and Fan speeds since it GB have some proprietary naming conventions
